### ISSUE TITLE
CUDA version installation issue

### ISSUE THREAD

**Issue by mitkotak** [risi-kondor/GElib#10]
Hey was facing some trouble installing the CUDA version. I was able to install torch and cnine and made sure my `CUDA_HOME` variable was set.

Here's the installation dump https://gist.github.com/mitkotak/86e7394a8ffa246e9f0d129f807fcc3e

Thanks !

**Comment by risi-kondor** [comment]
Thanks, I’ll take a look at this, hopefully tomorrrow.

Risi

**Comment by mitkotak** [comment]
@risi-kondor Anything else I can report to help debug. Thanks !

**Comment by risi-kondor** [comment]
Sorry for the delay. It looks like at some point an experimental version of the SO3 classes leaked into the main branch. I have now removed them from the PyThon bindings and on my machine the package compiles. The tests in the ci_tests directory seem to run okay with pytest. 

The whole package needs to be cleaned up though, it is embarrassingly messy. It’s actually next on my todo list I’ll probably get down to it in the next few days.

Let me know if you manage to compile it now!

Risi

**Comment by mitkotak** [comment]
Works now thanks !
