### ISSUE TITLE
gelib_base star import overwrites python wrapper classes

### ISSUE THREAD

**Issue by agoscinski** [risi-kondor/GElib#4]
Hello,

the `from gelib_base import *` import in the [__init__.py](https://github.com/risi-kondor/GElib/blob/91baf53a002d8c9a9f17624ddcaab8e1ecfe24ff/python/src/gelib/__init__.py#L4) is overwriting all Python wrapper classes. So for example when I use `gelib.SO3vec` it is from the shared lib `gelib_base` and not `gelib`

```python

In [1]: import gelib
Initializing GElib without GPU support.

In [2]: gelib.SO3vec
Out[2]: gelib_base.SO3vec
In [3]: gelib.SO3vec.randn
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 gelib.SO3vec.randn

AttributeError: type object 'gelib_base.SO3vec' has no attribute 'randn'

```

I commented out the gelib_base import in this [PR](https://github.com/risi-kondor/GElib/pull/3) and it then it works

```python
In [1]: import gelib
Initializing GElib without GPU support.

In [2]: gelib.SO3vec.randn
Out[2]: <bound method SO3vec.randn of <class 'gelib.SO3vec.SO3vec'>>
```

**Comment by risi-kondor** [comment]
Ah, I guess it is an unsafe practice to import `*`. It used to work, but now there is a class called `SO3vec` on the backend too and that breaks some of the earlier code. We'll fix this.

**Comment by agoscinski** [comment]
I can also do a PR to fix this if you want. Shouldn't be much more that replacing the import everywhere.

**Comment by agoscinski** [comment]
I started to move the examples to the the docstring so they can be run with 
```
pytest --doctest-modules --pyargs gelib
```
I would also add a GitHub Action that runs the test, so the tests are run for each pull request, so if a pull request breaks the library one can see it before merging

Is this okay for you if I add these things?

**Comment by risi-kondor** [comment]
I believe I fixed this import issue now. Please let me know if there is something else that does not work!

**Comment by agoscinski** [comment]
The example works now, but some tests are failing, see #5 for more information. I close this issue, because the import bug has been fixed
